/* Generated by the Nim Compiler v1.9.5 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function toJSStr(s_33556897) {
  var result_33556898 = null;

    var res_33556939 = newSeq_33556915((s_33556897).length);
    var i_33556940 = 0;
    var j_33556941 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556940 < (s_33556897).length)) break Label2;
          var c_33556942 = s_33556897[i_33556940];
          if ((c_33556942 < 128)) {
          res_33556939[j_33556941] = String.fromCharCode(c_33556942);
          i_33556940 += 1;
          }
          else {
            var helper_33556955 = newSeq_33556915(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556956 = c_33556942.toString(16);
                  if ((((code_33556956) == null ? 0 : (code_33556956).length) == 1)) {
                  helper_33556955.push("%0");;
                  }
                  else {
                  helper_33556955.push("%");;
                  }
                  
                  helper_33556955.push(code_33556956);;
                  i_33556940 += 1;
                  if ((((s_33556897).length <= i_33556940) || (s_33556897[i_33556940] < 128))) {
                  break Label3;
                  }
                  
                  c_33556942 = s_33556897[i_33556940];
                }
            };
++excHandler;
            try {
            res_33556939[j_33556941] = decodeURIComponent(helper_33556955.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556939[j_33556941] = helper_33556955.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556941 += 1;
        }
    };
    if (res_33556939.length < j_33556941) { for (var i = res_33556939.length ; i < j_33556941 ; ++i) res_33556939.push(null); }
               else { res_33556939.length = j_33556941; };
    result_33556898 = res_33556939.join("");

  return result_33556898;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_33556915(len_33556917) {
  var result_33556918 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/nim/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 625;
    F.filename = "system.nim";
    result_33556918 = new Array(len_33556917); for (var i = 0 ; i < len_33556917 ; ++i) { result_33556918[i] = null; }  framePtr = F.prev;

  return result_33556918;

}

function HEX3Aanonymous_654311427() {
  var F = {procname: "jscore_examples_3.:anonymous", prev: framePtr, filename: "/home/runner/work/nim/nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
  framePtr = F;
    F.line = 153;
    F.filename = "jscore.nim";
    rawEcho([77,105,99,114,111,116,97,115,107]);
  framePtr = F.prev;

  
}
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/nim/nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
F.line = 153;
F.filename = "jscore.nim";
queueMicrotask(HEX3Aanonymous_654311427);
framePtr = F.prev;
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/nim/nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/nim/nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/nim/nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
